base_images:
  ansible:
    name: "4.10"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.10"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.10"
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.10"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.10"
  tools:
    name: "4.10"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.10"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    prerelease:
      architecture: amd64
      product: ocp
      relative: 1
      version_bounds:
        lower: 4.10.0
        upper: 4.11.0-0
  target:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.10.0
        upper: 4.11.0-0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: azure-aro-cert-rotation-p1-f1
  cron: 9 7 * * *
  steps:
    cluster_profile: azure-qe
    env:
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.10 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.10 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-cert-rotation
    workflow: cucushift-installer-rehearse-azure-aro
zz_generated_metadata:
  branch: release-4.10
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable-4.10-upgrade-from-stable-4.10
